import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/templates/Navbar";
import { poppins } from "./fonts/GoogleFont";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-white antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
